// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/me.get').default>>>>
    }
    '/auth/sign-in': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/sign-in.post').default>>>>
    }
    '/auth/sign-out': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/sign-out.post').default>>>>
    }
    '/auth/sign-up': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/sign-up.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@4.4.8_382b60f2b13a1554aa3d656b049ddcfe/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+icon@2.3.1_magicast@0.5.3_vite@7.3.5_@types+node@25.9.4_jiti@2.7.0_lightningcss@1_67f583050759b4c190c36ac7517fd598/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}